import Image from "next/image";
import Link from "next/link";
import { Award, CheckCircle2, Clock3, Factory, FlaskConical, Gauge, PackageCheck, Recycle, ShieldCheck, Truck, Users } from "lucide-react";
import { SectionHead } from "@/components/ui/kaybaks-blocks";

const steps=[[FlaskConical,"01 Analiz","İhtiyacınızı analiz ediyor, en uygun çözümü belirliyoruz."],[PackageCheck,"02 Tasarım","Ambalajınıza özel tasarım ve ön çalışma hazırlıyoruz."],[Factory,"03 Üretim","Modern tesisimizde üretimi gerçekleştiriyoruz."],[ShieldCheck,"04 Kalite Kontrol","Her ürün kalite standartlarına göre test edilir."],[Truck,"05 Sevkiyat","Zamanında ve güvenli sevkiyat ile teslimat sağlıyoruz."]];
const machines=[["Otomatik Oluklu Hat","Yüksek hızda oluklu mukavva üretimi","/media/kaybaks-video-2.png"],["Bobin Ebatlama","Hassas kesim ve ebatlama çözümleri","/media/kaybaks-video-3-hd.jpg"],["Flexo Baskı Makinesi","Yüksek kaliteli baskı teknolojisi","/media/kaybaks-video-1.png"],["Otomatik Kesim Makinesi","Hızlı ve hassas kesim teknolojisi","/media/kaybaks-video-4.png"],["Laminasyon Makinesi","Dayanıklılığı artıran laminasyon","/media/kaybaks-video-5.png"]];

export default function QualityPage(){return <>
  <section className="quality-hero"><div className="container quality-hero-grid"><div className="hero-copy"><span className="eyebrow">Üretim & Kalite</span><h1>Kaliteden Ödün Vermeyen<br/><span className="yellow">Üretim</span> Anlayışı</h1><p>Modern üretim tesisimizde ileri teknoloji makineler ve tecrübeli ekibimizle, her aşamada kaliteyi merkezde tutarak üretim gerçekleştiriyoruz.</p><div className="hero-actions"><span className="arrow-link"><Gauge size={18}/> Yüksek Üretim Kapasitesi</span><span className="arrow-link"><Truck size={18}/> Güvenilir Teslimat</span><span className="arrow-link"><Recycle size={18}/> Sürdürülebilir Üretim</span></div></div><div className="quality-visual"><Image src="/media/kaybaks-video-2.png" alt="KAYBAKS üretim tesisi" width={800} height={500}/><div className="quality-note"><strong>Kalite ve Güven</strong><small style={{display:"block",color:"#68707a"}}>Her kutuda Kaybaks kalitesi</small></div></div></div></section>
  <section className="section"><div className="container two-col"><div className="photo-collage"><Image className="big" src="/media/kaybaks-factory-hd.jpg" alt="KAYBAKS üretim tesisi" width={936} height={494}/><Image src="/media/products/corrugated-sheet.png" alt="Oluklu mukavva" width={500} height={350}/><Image src="/media/kaybaks-video-4.png" alt="Üretim" width={500} height={350}/></div><div className="content-block"><span className="kicker">Kaybaks Üretim Anlayışı</span><h2>Her Aşamada Mükemmellik</h2><p>KAYBAKS, oluklu mukavva ve ambalaj üretiminde kaliteyi yalnızca bir hedef değil, bir standart olarak benimser. Hammaddeden sevkiyata kadar tüm süreçlerimizi yüksek teknolojiye sahip makinelerimiz ve uzman ekibimiz tarafından titizlikle yönetiriz.</p><p>ISO standartlarına uygun üretim süreçlerimizle, ürünlerimizin dayanıklılığını ve çevreye duyarlılığını garanti altına alıyoruz.</p><div className="stats-inline"><div className="stat"><strong>Yüksek Teknoloji</strong><small>Tam otomasyonlu üretim hatları</small></div><div className="stat"><strong>Kalite Odaklı</strong><small>Sürekli iyileştirme</small></div><div className="stat"><strong>Deneyimli Kadro</strong><small>Alanında uzman ekip</small></div><div className="stat"><strong>Müşteri Memnuniyeti</strong><small>İhtiyacınıza özel çözümler</small></div></div></div></div></section>
  <section className="section-sm soft-section"><div className="container"><SectionHead kicker="Üretim Sürecimiz" title="5 Adımda Mükemmel Üretim"/><div className="process-cards">{steps.map(([I,t,p])=>{const Icon=I as typeof Factory;return <div className="process-card" key={t as string}><div className="icon-circle"><Icon size={22}/></div><h3>{t as string}</h3><p>{p as string}</p></div>})}</div></div></section>
  <section className="section"><div className="container"><SectionHead kicker="Teknolojik Üretim Altyapımız" title="Modern Makineler, Üstün Verimlilik"/><div className="machine-grid">{machines.map(([t,p,src])=><div className="machine" key={t}><Image src={src} alt={t} width={500} height={330}/><h3>{t}</h3><p>{p}</p></div>)}</div></div></section>
  <section className="section-sm soft-section"><div className="container standards"><div><span className="small-kicker">Kalite Standartlarımız</span><h2>Uluslararası Standartlarda Üretim</h2><p style={{color:"#68707a",fontSize:11}}>Tüm üretim süreçlerimiz, uluslararası kalite standartlarına uygun olarak gerçekleştirilmektedir.</p><ul className="standard-list"><li>🟡 ISO 9001:2015 Kalite Yönetim Sistemi</li><li>🟡 ISO 14001:2015 Çevre Yönetim Sistemi</li><li>🟡 ISO 45001:2018 İş Sağlığı ve Güvenliği</li><li>🟡 FSC® ve Geri Dönüşüm Uyumlu Üretim</li></ul></div><div className="benefit-list">{[[ShieldCheck,"Dayanıklı Ambalaj","Ürünlerinizi darbelere ve dış etkenlere karşı korur."],[Recycle,"Çevre Dostu Üretim","Geri dönüştürülebilir malzemelerle doğaya duyarlı üretim."],[Truck,"Zamanında Teslimat","Planlı üretim ve güçlü lojistik ağımızla zamanında teslim."]].map(([I,t,p])=>{const Icon=I as typeof ShieldCheck;return <div className="benefit-row" key={t as string}><div className="icon-circle"><Icon size={20}/></div><div><h3>{t as string}</h3><p>{p as string}</p></div></div>})}</div></div></section>
  <section className="section-sm"><div className="container feature-strip-grid">{[[Factory,"10.000+","Ton / Yıl Üretim Kapasitesi"],[Users,"150+","Müşteri Portföyü"],[Clock3,"7/24","Üretim İmkanı"],[PackageCheck,"Geniş Ürün Yelpazesi","Her sektöre özel çözümler"]].map(([I,n,t])=>{const Icon=I as typeof Factory;return <div className="mini-feature" key={n as string}><div className="icon-circle"><Icon size={20}/></div><div><h3>{n as string}</h3><p>{t as string}</p></div></div>})}</div></section>
  <section className="section-sm" style={{background:"#22272e",color:"#fff"}}><div className="container" style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:20}}><div><h2>Kaliteli Üretim İçin Doğru Adrestesiniz</h2><p style={{color:"#ccd0d5"}}>Ürünleriniz ve üretim süreçleriniz hakkında detaylı bilgi almak için bize ulaşın.</p></div><Link className="btn btn-primary" href="/iletisim#teklif">Teklif Al</Link></div></section>
  </>}
