import { Clock3, Mail, MapPin, PackageCheck, Phone, Ruler, Send, Truck } from "lucide-react";
import { getSettings } from "@/lib/content-store";
import { KraftImage, Kicker } from "@/components/ui/kraft";

export const dynamic = "force-dynamic";

export default async function ContactPage({ searchParams }: { searchParams: Promise<{ urun?: string }> }) {
  const [settings, query] = await Promise.all([getSettings(), searchParams]);
  const selectedProduct = query.urun || "";
  return <>
    <section className="kp-contact-hero kp-paper-grid"><div className="kp-container kp-contact-hero-grid"><div><Kicker>İletişim</Kicker><h1>Doğru ambalaj için<br /><span>ilk adımı birlikte atalım.</span></h1><p>İhtiyacınızı dinleyelim, ürününüze en uygun ve güvenilir ambalaj çözümünü birlikte planlayalım.</p></div><div className="kp-natural-frame"><KraftImage src="/media/contact-factory-hero.png" alt="KAYBAKS fabrika binası" width={1942} height={809} priority /></div></div></section>

    <section className="kp-section" id="teklif"><div className="kp-container kp-contact-layout"><form className="kp-contact-form" action={`mailto:${settings.email}`} method="post" encType="text/plain"><div className="kp-form-title"><h2>Teklif talebinizi <span>gönderin.</span></h2><p>Ürününüzü, kullanım amacınızı ve adet bilgilerinizi paylaşın.</p></div><div className="kp-form-grid"><label>Ad Soyad<input name="ad_soyad" autoComplete="name" required /></label><label>Firma Adı<input name="firma" autoComplete="organization" required /></label><label>Telefon<input name="telefon" type="tel" autoComplete="tel" required /></label><label>E-posta<input name="email" type="email" autoComplete="email" required /></label><label>İlgilendiğiniz Ürün<select name="urun" defaultValue={selectedProduct}><option value="">Ürün seçin</option><option>Oluklu Mukavva Levha</option><option>Normal Kutu</option><option>Teleskopik Kutu</option><option>Kalıp Kesim Kutu</option><option>Ondüle Ürünler</option><option>Demonte Mobilya Kutuları</option><option>Özel Ölçü Kutu</option><option>Özel Tasarım Ambalaj</option></select></label><label>Tahmini Adet<input name="adet" inputMode="numeric" /></label><label className="kp-field-full">Mesajınız<textarea name="mesaj" rows={6} placeholder="Ölçü, kullanım amacı ve diğer detaylar..." required /></label><label className="kp-consent kp-field-full"><input type="checkbox" required />KVKK metnini okudum ve kabul ediyorum.</label><button className="kp-button kp-button-yellow kp-field-full" type="submit">Teklif Talebi Gönder<Send size={17} /></button></div></form>

      <aside className="kp-contact-card"><div className="kp-contact-card-head"><h2>Bize <span>Ulaşın</span></h2><p>Sorularınız, talepleriniz veya iş birliği fırsatları için bizimle iletişime geçebilirsiniz.</p></div><div className="kp-contact-lines"><p><MapPin />{settings.address}</p><a href={`tel:${settings.phone_href}`}><Phone />{settings.phone}</a><a href={`mailto:${settings.email}`}><Mail />{settings.email}</a><p><Clock3 />Hafta içi 08:30 – 18:00<br />Cumartesi 08:30 – 13:00</p></div><div className="kp-map-card"><div className="kp-map-grid" aria-hidden="true"><i /><i /><i /><i /><i /></div><span><MapPin />KAYBAKS<br /><small>1. Organize Sanayi Bölgesi · Kayseri</small></span></div></aside></div></section>

    <section className="kp-section kp-paper-grid"><div className="kp-container kp-offer-requirements"><div><Kicker>Teklif için ne gerekli?</Kicker><h2>Üç bilgiyle başlayabiliriz.</h2><p>Doğru ve hızlı bir teklif hazırlayabilmemiz için temel bilgileri paylaşmanız yeterli.</p></div><article><KraftImage src="/media/products/corrugated-sheet.png" alt="Ambalaj ölçüsü" /><span>1</span><Ruler /><h3>Ölçü</h3><p>Ürünün en, boy ve yükseklik ölçüleri.</p></article><article><KraftImage src="/media/products/die-cut-box.png" alt="Ambalaj kullanım alanı" /><span>2</span><PackageCheck /><h3>Kullanım alanı</h3><p>Ürünün hangi amaçla kullanılacağı.</p></article><article><KraftImage src="/media/kaybaks-video-4.png" alt="Ambalaj sevkiyat adedi" /><span>3</span><Truck /><h3>Tahmini adet</h3><p>İhtiyaç duyulan yaklaşık ürün adedi.</p></article></div></section>

    <section className="kp-call-band"><div className="kp-container"><div><h2>Acil bir talebiniz mi var?</h2><p>Hemen arayarak ekibimize ulaşın.</p></div><a className="kp-button kp-button-yellow" href={`tel:${settings.phone_href}`}><Phone size={18} />Hemen Ara</a><strong>{settings.phone}</strong></div></section>
  </>;
}
